# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('medida', models.IntegerField()),
                ('stock_local', models.IntegerField(null=True)),
                ('stock_deposito', models.IntegerField(null=True)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField(null=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='sistema.Categoria')),
                ('estado', models.ForeignKey(db_column='id_estado_producto', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoProducto')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.CASCADE, to='sistema.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('key_session', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_desde', models.DateTimeField(null=True)),
                ('fecha_hora_hasta', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('codigo', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='sistema.Categoria')),
                ('estado', models.ForeignKey(db_column='id_estado_subcategoria', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoSubCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField(null=True)),
                ('estado', models.ForeignKey(db_column='id_estado_unidad_medidad', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoUnidadMedida')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=40)),
                ('contrasenia', models.CharField(max_length=40)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField(null=True)),
                ('estado', models.ForeignKey(db_column='id_estado_usuario', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoUsuario')),
                ('pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.CASCADE, to='sistema.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='sesionusuario',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(db_column='id_subcategoria', on_delete=django.db.models.deletion.CASCADE, to='sistema.SubCategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(db_column='id_unidad_medida', on_delete=django.db.models.deletion.CASCADE, to='sistema.UnidadMedida'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.ForeignKey(db_column='id_estado_categoria', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoCategoria'),
        ),
    ]
