# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEstadoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField(null=True)),
                ('estado', models.ForeignKey(db_column='id_estado_usuario', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('habilitado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.CASCADE, to='sistema.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateTimeField(null=True)),
                ('fecha_hasta', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=40)),
                ('contrasenia', models.CharField(max_length=40)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField(null=True)),
                ('estado', models.ForeignKey(db_column='id_estado_usuario', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoUsuario')),
                ('pregunta', models.ForeignKey(db_column='id_pregunta', on_delete=django.db.models.deletion.CASCADE, to='sistema.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
        ),
        migrations.AddField(
            model_name='historicoestadousuario',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
        ),
    ]
