# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestapregunta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sesionusuario',
            name='fecha_ultimo_inicio',
        ),
        migrations.RemoveField(
            model_name='sesionusuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='respuestapregunta',
            name='id_respuesta_pregunta',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
