# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesionusuario',
            old_name='fecha_desde',
            new_name='fecha_hora_desde',
        ),
        migrations.RenameField(
            model_name='sesionusuario',
            old_name='fecha_hasta',
            new_name='fecha_hora_hasta',
        ),
        migrations.RemoveField(
            model_name='sesionusuario',
            name='id',
        ),
        migrations.AddField(
            model_name='sesionusuario',
            name='fecha_hora_ultima_conexion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sesionusuario',
            name='key_session',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
