# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20180721_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_desde',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_hasta',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(db_column='id_subcategoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.SubCategoria'),
        ),
    ]
