# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20180721_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('codigo', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComboDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('combo', models.ForeignKey(db_column='id_combo', on_delete=django.db.models.deletion.CASCADE, to='sistema.Combo')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='estado',
            field=models.ForeignKey(db_column='id_estado_combo', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoCombo'),
        ),
    ]
