# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_sesionusuario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesionusuario',
            old_name='fecha_hora_ultima_conexion',
            new_name='fecha_hora_inicio_ultima_conexion',
        ),
    ]
