# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20180728_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoListaPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('codigo', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('vigencia_desde', models.DateTimeField()),
                ('vigencia_hasta', models.DateTimeField(null=True)),
                ('estado', models.ForeignKey(db_column='id_estado_lista_precio', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoListaPrecio')),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecioDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario_compra', models.IntegerField()),
                ('margen_ganacia', models.IntegerField()),
                ('precio_unitario_venta', models.IntegerField()),
                ('lista_precio', models.ForeignKey(db_column='id_lista_precio', on_delete=django.db.models.deletion.CASCADE, to='sistema.ListaPrecio')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='combodetalle',
            name='precio_producto_combo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
