# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20180728_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listapreciodetalle',
            name='margen_ganacia',
        ),
    ]
