# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_remove_listapreciodetalle_margen_ganacia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('total_apertura', models.IntegerField()),
                ('total_cierre', models.IntegerField()),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CajaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('caja', models.ForeignKey(db_column='id_caja', on_delete=django.db.models.deletion.CASCADE, to='sistema.Caja')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicasFormaPago',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCaracteristicasFormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_caracteristica', models.CharField(max_length=60)),
                ('caracteristicas_forma_pago', models.ForeignKey(db_column='id_caracteristica', on_delete=django.db.models.deletion.CASCADE, to='sistema.CaracteristicasFormaPago')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoFormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMovimientoCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMovimientoStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTipoMovimientoCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTipoMovimientoStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoFormaPago')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCapital',
            fields=[
                ('codigo', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoTipoMovimientoCapital')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('codigo', models.IntegerField(default=1000, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
                ('total_parcial', models.IntegerField()),
                ('total_final', models.IntegerField()),
                ('descuento', models.IntegerField(null=True)),
                ('estado', models.ForeignKey(db_column='id_estado_movimiento', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoMovimientoStock')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStockDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('movimiento_stock', models.ForeignKey(db_column='id_movimiento_stock', on_delete=django.db.models.deletion.CASCADE, to='sistema.MovimientoStock')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimientoCapital',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoTipoMovimientoCapital')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimientoStock',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoTipoMovimientoStock')),
            ],
        ),
        migrations.AddField(
            model_name='combodetalle',
            name='margen_ganancia_producto_combo',
            field=models.IntegerField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='tipo_movimiento',
            field=models.ForeignKey(db_column='id_tipo_movimiento', on_delete=django.db.models.deletion.CASCADE, to='sistema.TipoMovimientoStock'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
        ),
        migrations.AddField(
            model_name='movimientocapital',
            name='movimiento_stock',
            field=models.ForeignKey(db_column='id_movimiento_stock', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.MovimientoStock'),
        ),
        migrations.AddField(
            model_name='movimientocapital',
            name='tipo_movimiento',
            field=models.ForeignKey(db_column='id_tipo_movimiento', on_delete=django.db.models.deletion.CASCADE, to='sistema.TipoMovimientoCapital'),
        ),
        migrations.AddField(
            model_name='detallecaracteristicasformapago',
            name='forma_pago',
            field=models.ForeignKey(db_column='id_forma_pago', on_delete=django.db.models.deletion.CASCADE, to='sistema.FormaPago'),
        ),
        migrations.AddField(
            model_name='cajadetalle',
            name='movimiento_capital',
            field=models.ForeignKey(db_column='id_movimiento', on_delete=django.db.models.deletion.CASCADE, to='sistema.MovimientoCapital'),
        ),
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoCaja'),
        ),
    ]
