# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20180730_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
