# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_auto_20180824_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocapital',
            name='usuraio',
            field=models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Usuario'),
        ),
    ]
