# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-22 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_movimientocapital_usuraio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientocapital',
            old_name='usuraio',
            new_name='usuario',
        ),
    ]
