# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-09 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_auto_20180924_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostockdetalle',
            name='combo',
            field=models.ForeignKey(db_column='id_combo', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Combo'),
        ),
        migrations.AlterField(
            model_name='movimientostockdetalle',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
    ]
