# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_auto_20181008_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Cliente'),
        ),
    ]
