# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_estadosorteo_sorteo_sorteodetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorteo',
            old_name='fecha_sorteo',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='sorteo',
            name='estado',
            field=models.ForeignKey(db_column='id_estado', default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.EstadoSorteo'),
            preserve_default=False,
        ),
    ]
