# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-20 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0023_movimientostockdetalle_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientostock',
            name='forma_pago',
            field=models.ForeignKey(db_column='id_forma_pago', default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.FormaPago'),
            preserve_default=False,
        ),
    ]
